<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Mon premier site web en php</title>
    <link href="css/style.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <?php require_once 'section/entete.phtml'; ?>

    <?php require_once 'section/menu.phtml'; ?>

    <div id="contenu">
        <?php require_once 'section/retroaction.phtml'; ?>

        <div class="sautligne">
            <table>
                <tr>
                    <th>Tag</th>
                    <th></th>
                    <th></th>
                </tr>

                <?php
                foreach ($tags as $tag)
                {
                ?>
                    <tr>
                        <td><?= $tag->getNom() ?></td>

                        <td>
                            <form name="modifierTag" action="index.php" method="post">
                                <input type="hidden" name="id" value="<?= $tag->getId() ?>">
                                <input type="hidden" name="ctrl" value="tag">
                                <input type="hidden" name="action" value="demandeModification">
                                <input type="submit" name="boutonDemandeModification" value="Modifier">
                            </form>
                        </td>

                        <td>
                            <form name="supprimerTag" action="index.php" method="post">
                                <input type="hidden" name="id" value="<?= $tag->getId() ?>">
                                <input type="hidden" name="ctrl" value="tag">
                                <input type="hidden" name="action" value="supprimer">
                                <input type="submit" name="boutonSupprimer" value="Supprimer">
                            </form>
                        </td>
                    </tr>
                <?php
                }
                ?>
            </table>
        </div>

        <div class="sautligne">
            <?php
            if (isset($tagAModifier))
            {
            ?>
                <form name="modifierTag" action="index.php" method="post">
                    <label>Tag à modifier : <input type="text" name="nomTag" value="<?= isset($nomTag)?$nomTag:"" ?>"></label>
                    <input type="hidden" name="id" value="<?= $tagAModifier->getId() ?>">
                    <input type="hidden" name="ctrl" value="tag">
                    <input type="hidden" name="action" value="modifier">
                    <input type="submit" name="boutonModifier" value="Modifier">
                    <input type="submit" name="boutonAnnuler" value="Annuler">
                </form>
            <?php
            }
            else
            {
            ?>
                <form name="ajouterTag" action="index.php" method="post">
                    <input type="hidden" name="ctrl" value="tag">
                    <input type="hidden" name="action" value="ajouter">
                    <label>Nouveau tag : <input type="text" name="nomTag" value="<?= isset($nomTag)?$nomTag:"" ?>"></label>
                    <input type="submit" name="boutonAjouter" value="Ajouter">
                </form>
            <?php
            }
            ?>
        </div>
    </div>

    <?php require_once 'section/pied.phtml'; ?>
</body>
</html>
